server:
  port: 8079

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freedesk_user_service
    username: springstudent
    password: springstudent
  application:
    name: tokenservice

app:
  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret: sBnlg0BGosgPMQju